{% set version = "1.1.0" %}

package:
  name: plutovg
  version: {{ version }}

source:
  url: https://github.com/sammycage/plutovg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8aa9860519c407890668c29998e8bb88896ef6a2e6d7ce5ac1e57f18d79e1525

build:
  number: 0
  run_exports:
    # 0-ver, so lets just pin to the patch version for now
    - {{ pin_subpackage('plutovg', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - meson
    - ninja
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/plutovg/plutovg.h                     # [unix]
    - test -f ${PREFIX}/lib/libplutovg${SHLIB_EXT}                    # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/plutovg.pc                      # [unix]
    - if not exist %PREFIX%\Library\include\plutovg\plutovg.h exit 1  # [win]
    - if not exist %PREFIX%\Library\lib\plutovg.lib exit 1            # [win]
    - if not exist %PREFIX%\Library\lib\pkgconfig\plutovg.pc exit 1   # [win]
    - if not exist %PREFIX%\Library\bin\plutovg-1.dll exit 1          # [win]

about:
  home: https://github.com/sammycage/plutovg
  summary: 'PlutoVG is a standalone 2D vector graphics library in C.'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
